# Generated by Django 5.1.3 on 2024-11-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='test_password', max_length=128),
            preserve_default=False,
        ),
    ]
