# Generated by Django 5.1.3 on 2024-11-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f16app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
